---
- name: Test Slack Callback Plugin
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Successful Task
      debug:
        msg: "This task will succeed"

    - name: Failing Task
      command: /bin/false
      ignore_errors: yes

    - name: Skipped Task
      debug:
        msg: "This task will be skipped"
      when: false